# Generated by Django 5.0 on 2024-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0002_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
