# Generated by Django 5.0 on 2024-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0003_publicacion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='urlImagen',
            field=models.ImageField(upload_to='publicaciones/'),
        ),
    ]
