# Generated by Django 5.0 on 2024-05-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0004_alter_imagen_urlimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.ImageField(default='perfil_images/default.jpg', upload_to='perfil_images/'),
        ),
    ]
