# Generated by Django 5.0 on 2024-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0005_alter_perfil_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='', upload_to='perfil_images/'),
        ),
    ]
