# Generated by Django 5.0 on 2024-05-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0006_alter_perfil_fotoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbdd.perfil')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbdd.publicacion')),
            ],
            options={
                'unique_together': {('perfil', 'publicacion')},
            },
        ),
    ]
