# Generated by Django 5.0 on 2024-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0008_perfil_delete_post_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotoPerfil',
            field=models.CharField(max_length=255, verbose_name='Foto de perfil'),
        ),
    ]
