# Generated by Django 5.0 on 2024-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0008_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='numSeguidores',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='numSeguidos',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='totalPublicaciones',
        ),
        migrations.AddField(
            model_name='perfil',
            name='siguiendo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='bbdd.perfil'),
        ),
    ]
