# Generated by Django 4.2.5 on 2024-05-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0011_alter_publicacion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajedirecto',
            name='user',
        ),
        migrations.AddField(
            model_name='mensajedirecto',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='bbdd.sala'),
        ),
    ]
