# Generated by Django 4.2.5 on 2024-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0012_remove_mensajedirecto_user_mensajedirecto_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
