# Generated by Django 4.2.5 on 2024-05-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0013_sala_nombre_mascota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='nombre_mascota',
            new_name='nombre_mascota_emisor',
        ),
        migrations.AddField(
            model_name='sala',
            name='nombre_mascota_receptor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
